<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TemplateSeeder extends Seeder
{
    public function run(): void
    {
        $templates = [
            // Email Templates
            [
                'id' => 1,
                'name' => 'Invoice Generated',
                'code' => 'INVOICE_GENERATED',
                'type' => 'email',
                'subject' => 'Tagihan Internet {{brand_name}} - {{invoice_no}}',
                'content' => "Yth. {{customer_name}},\n\nBerikut adalah tagihan internet Anda untuk periode {{period_start}} - {{period_end}}:\n\nNomor Invoice: {{invoice_no}}\nTotal Tagihan:  Rp {{total_amount}}\nJatuh Tempo: {{due_date}}\n\nSilakan lakukan pembayaran sebelum tanggal jatuh tempo untuk menghindari pemutusan layanan.\n\nMetode Pembayaran:\n- Transfer Bank Mandiri:  {{bank_account_number}} a/n {{bank_account_name}}\n- Virtual Account:  Hubungi CS untuk mendapatkan nomor VA\n\nTerima kasih atas kepercayaan Anda menggunakan layanan {{brand_name}}.\n\nHormat kami,\n{{company_name}}",
                'variables' => json_encode(['customer_name', 'invoice_no', 'period_start', 'period_end', 'total_amount', 'due_date', 'brand_name', 'company_name', 'bank_account_number', 'bank_account_name']),
                'is_active' => true,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'name' => 'Payment Reminder H-7',
                'code' => 'REMINDER_H7',
                'type' => 'email',
                'subject' => 'Pengingat Pembayaran - {{invoice_no}} (7 hari lagi)',
                'content' => "Yth. {{customer_name}},\n\nKami ingin mengingatkan bahwa tagihan internet Anda akan jatuh tempo dalam 7 hari.\n\nNomor Invoice: {{invoice_no}}\nTotal Tagihan:  Rp {{total_amount}}\nJatuh Tempo:  {{due_date}}\n\nMohon segera lakukan pembayaran untuk menghindari gangguan layanan.\n\nTerima kasih,\n{{company_name}}",
                'variables' => json_encode(['customer_name', 'invoice_no', 'total_amount', 'due_date', 'company_name']),
                'is_active' => true,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'name' => 'Payment Reminder H-3',
                'code' => 'REMINDER_H3',
                'type' => 'email',
                'subject' => 'Pengingat Pembayaran - {{invoice_no}} (3 hari lagi)',
                'content' => "Yth. {{customer_name}},\n\nTagihan internet Anda akan segera jatuh tempo dalam 3 hari.\n\nNomor Invoice: {{invoice_no}}\nTotal Tagihan:  Rp {{total_amount}}\nJatuh Tempo:  {{due_date}}\n\nSegera lakukan pembayaran untuk menghindari penurunan kecepatan dan pemutusan layanan.\n\nTerima kasih,\n{{company_name}}",
                'variables' => json_encode(['customer_name', 'invoice_no', 'total_amount', 'due_date', 'company_name']),
                'is_active' => true,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'name' => 'Payment Reminder H-1',
                'code' => 'REMINDER_H1',
                'type' => 'email',
                'subject' => 'PENTING: Tagihan Jatuh Tempo Besok - {{invoice_no}}',
                'content' => "Yth. {{customer_name}},\n\nINI ADALAH PENGINGAT TERAKHIR.\n\nTagihan internet Anda akan jatuh tempo BESOK.\n\nNomor Invoice:  {{invoice_no}}\nTotal Tagihan: Rp {{total_amount}}\nJatuh Tempo: {{due_date}}\n\nJika pembayaran tidak diterima, layanan Anda akan mengalami penurunan kecepatan dan kemungkinan pemutusan.\n\nSegera hubungi kami jika ada kendala pembayaran.\n\nTerima kasih,\n{{company_name}}",
                'variables' => json_encode(['customer_name', 'invoice_no', 'total_amount', 'due_date', 'company_name']),
                'is_active' => true,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'name' => 'Pre Soft-Limit Warning',
                'code' => 'PRE_SOFTLIMIT',
                'type' => 'email',
                'subject' => 'PERINGATAN: Kecepatan Internet Akan Diturunkan - {{invoice_no}}',
                'content' => "Yth. {{customer_name}},\n\nTagihan internet Anda telah melewati jatuh tempo dan belum dibayar.\n\nNomor Invoice: {{invoice_no}}\nTotal Tagihan: Rp {{total_amount}}\nJatuh Tempo: {{due_date}}\n\nJika pembayaran tidak diterima dalam 24 jam, kecepatan internet Anda akan DITURUNKAN menjadi 50% dari kecepatan normal.\n\nSegera lakukan pembayaran untuk menghindari penurunan layanan.\n\nTerima kasih,\n{{company_name}}",
                'variables' => json_encode(['customer_name', 'invoice_no', 'total_amount', 'due_date', 'company_name']),
                'is_active' => true,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'name' => 'Pre Suspend Warning',
                'code' => 'PRE_SUSPEND',
                'type' => 'email',
                'subject' => 'PERINGATAN TERAKHIR: Layanan Akan Diputus - {{invoice_no}}',
                'content' => "Yth. {{customer_name}},\n\nTagihan internet Anda telah lama melewati jatuh tempo.\n\nNomor Invoice:  {{invoice_no}}\nTotal Tagihan: Rp {{total_amount}}\nJatuh Tempo: {{due_date}}\n\nJika pembayaran tidak diterima dalam 24 jam, layanan internet Anda akan DIPUTUS SEMENTARA.\n\nUntuk mengaktifkan kembali layanan, silakan lakukan pembayaran dan hubungi Customer Service kami.\n\nTerima kasih,\n{{company_name}}",
                'variables' => json_encode(['customer_name', 'invoice_no', 'total_amount', 'due_date', 'company_name']),
                'is_active' => true,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'name' => 'Payment Received',
                'code' => 'PAYMENT_RECEIVED',
                'type' => 'email',
                'subject' => 'Pembayaran Diterima - {{invoice_no}}',
                'content' => "Yth. {{customer_name}},\n\nTerima kasih!  Pembayaran Anda telah kami terima.\n\nNomor Invoice: {{invoice_no}}\nJumlah Dibayar: Rp {{amount_paid}}\nTanggal Pembayaran:  {{payment_date}}\nMetode Pembayaran: {{payment_method}}\n\nTerima kasih atas kepercayaan Anda menggunakan layanan {{brand_name}}.\n\nHormat kami,\n{{company_name}}",
                'variables' => json_encode(['customer_name', 'invoice_no', 'amount_paid', 'payment_date', 'payment_method', 'brand_name', 'company_name']),
                'is_active' => true,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // SMS Templates
            [
                'id' => 8,
                'name' => 'SMS Payment Reminder',
                'code' => 'SMS_REMINDER',
                'type' => 'sms',
                'subject' => null,
                'content' => "{{brand_name}}:  Tagihan {{invoice_no}} Rp{{total_amount}} jatuh tempo {{due_date}}.  Segera bayar utk hindari gangguan layanan.  Info:  {{company_phone}}",
                'variables' => json_encode(['brand_name', 'invoice_no', 'total_amount', 'due_date', 'company_phone']),
                'is_active' => true,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'name' => 'SMS Payment Received',
                'code' => 'SMS_PAYMENT_RECEIVED',
                'type' => 'sms',
                'subject' => null,
                'content' => "{{brand_name}}: Pembayaran {{invoice_no}} Rp{{amount_paid}} telah diterima. Terima kasih! ",
                'variables' => json_encode(['brand_name', 'invoice_no', 'amount_paid']),
                'is_active' => true,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // WhatsApp Templates
            [
                'id' => 10,
                'name' => 'WhatsApp Invoice Notification',
                'code' => 'WA_INVOICE',
                'type' => 'whatsapp',
                'subject' => null,
                'content' => "Halo {{customer_name}} 👋\n\nTagihan internet *{{brand_name}}* Anda telah terbit:\n\n📄 *Invoice: * {{invoice_no}}\n💰 *Total:* Rp {{total_amount}}\n📅 *Jatuh Tempo:* {{due_date}}\n\n*Metode Pembayaran:*\n🏦 Transfer:  {{bank_name}} {{bank_account_number}} a/n {{bank_account_name}}\n\nAbaikan pesan ini jika sudah membayar.\n\nTerima kasih!  🙏",
                'variables' => json_encode(['customer_name', 'brand_name', 'invoice_no', 'total_amount', 'due_date', 'bank_name', 'bank_account_number', 'bank_account_name']),
                'is_active' => true,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 11,
                'name' => 'WhatsApp Payment Reminder',
                'code' => 'WA_REMINDER',
                'type' => 'whatsapp',
                'subject' => null,
                'content' => "Halo {{customer_name}} 👋\n\n⏰ *Pengingat Pembayaran*\n\nTagihan internet Anda akan jatuh tempo {{days_remaining}}.\n\n📄 *Invoice:* {{invoice_no}}\n💰 *Total:* Rp {{total_amount}}\n📅 *Jatuh Tempo:* {{due_date}}\n\nSegera lakukan pembayaran ya!  🙏\n\nTerima kasih,\n*{{brand_name}}*",
                'variables' => json_encode(['customer_name', 'days_remaining', 'invoice_no', 'total_amount', 'due_date', 'brand_name']),
                'is_active' => true,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 12,
                'name' => 'WhatsApp Payment Received',
                'code' => 'WA_PAYMENT_RECEIVED',
                'type' => 'whatsapp',
                'subject' => null,
                'content' => "Halo {{customer_name}} 👋\n\n✅ *Pembayaran Berhasil! *\n\n📄 Invoice: {{invoice_no}}\n💰 Jumlah:  Rp {{amount_paid}}\n📅 Tanggal: {{payment_date}}\n\nTerima kasih telah menggunakan *{{brand_name}}*!  🎉",
                'variables' => json_encode(['customer_name', 'invoice_no', 'amount_paid', 'payment_date', 'brand_name']),
                'is_active' => true,
                'created_by' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('templates')->insert($templates);
    }
}