<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class TicketSeeder extends Seeder
{
    public function run(): void
    {
        $tickets = [
            [
                'id' => 1,
                'ticket_number' => 'TKT-2026-01-0001',
                'customer_id' => 1,
                'subscription_id' => 1,
                'caller_name' => 'Ahmad Sudirman',
                'phone' => '081311111111',
                'email' => 'ahmad.sudirman@gmail.com',
                'category' => 'technical',
                'priority' => 'medium',
                'subject' => 'Internet lambat sejak kemarin',
                'description' => 'Kecepatan internet menurun drastis sejak kemarin malam.  Sudah coba restart modem tapi masih sama.',
                'status' => 'resolved',
                'assigned_to' => 4,
                'assigned_at' => Carbon::now()->subDays(3)->setHour(9)->setMinute(30),
                'resolved_at' => Carbon::now()->subDays(3)->setHour(14)->setMinute(15),
                'closed_at' => Carbon::now()->subDays(2),
                'sla_due_date' => Carbon::now()->subDays(2),
                'resolution_notes' => 'Masalah pada kabel distribusi. Sudah diperbaiki oleh tim NOC.',
                'customer_rating' => 5,
                'customer_feedback' => 'Respon cepat dan masalah teratasi. Terima kasih!',
                'created_by' => 4,
                'created_at' => Carbon::now()->subDays(3)->setHour(8)->setMinute(45),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'ticket_number' => 'TKT-2026-01-0002',
                'customer_id' => 3,
                'subscription_id' => 3,
                'caller_name' => 'Citra Dewi',
                'phone' => '081333333333',
                'email' => 'citra.dewi@gmail.com',
                'category' => 'billing',
                'priority' => 'low',
                'subject' => 'Pertanyaan tentang tagihan',
                'description' => 'Ingin menanyakan kenapa tagihan bulan ini berbeda dari bulan lalu.',
                'status' => 'closed',
                'assigned_to' => 3,
                'assigned_at' => Carbon::now()->subDays(5)->setHour(10)->setMinute(0),
                'resolved_at' => Carbon::now()->subDays(5)->setHour(10)->setMinute(30),
                'closed_at' => Carbon::now()->subDays(5)->setHour(11)->setMinute(0),
                'sla_due_date' => Carbon::now()->subDays(4),
                'resolution_notes' => 'Explained about promo period ended. Customer understood.',
                'customer_rating' => 4,
                'customer_feedback' => 'Penjelasan jelas, terima kasih.',
                'created_by' => 3,
                'created_at' => Carbon::now()->subDays(5)->setHour(9)->setMinute(30),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'ticket_number' => 'TKT-2026-01-0003',
                'customer_id' => 5,
                'subscription_id' => 5,
                'caller_name' => 'Eko Prasetyo',
                'phone' => '081355555555',
                'email' => 'eko.prasetyo@gmail.com',
                'category' => 'billing',
                'priority' => 'high',
                'subject' => 'Request aktivasi kembali setelah bayar',
                'description' => 'Saya sudah transfer pembayaran, mohon segera diaktifkan kembali layanannya.',
                'status' => 'in_progress',
                'assigned_to' => 3,
                'assigned_at' => Carbon::now()->subHours(2),
                'resolved_at' => null,
                'closed_at' => null,
                'sla_due_date' => Carbon:: now()->addHours(4),
                'resolution_notes' => null,
                'customer_rating' => null,
                'customer_feedback' => null,
                'created_by' => 4,
                'created_at' => Carbon::now()->subHours(3),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'ticket_number' => 'TKT-2026-01-0004',
                'customer_id' => 2,
                'subscription_id' => 2,
                'caller_name' => 'Budi Santoso',
                'phone' => '081322222222',
                'email' => 'budi.santoso@gmail.com',
                'category' => 'information',
                'priority' => 'low',
                'subject' => 'Tanya promo upgrade paket',
                'description' => 'Apakah ada promo untuk upgrade dari paket Basic ke Medium?',
                'status' => 'open',
                'assigned_to' => null,
                'assigned_at' => null,
                'resolved_at' => null,
                'closed_at' => null,
                'sla_due_date' => Carbon::now()->addDay(),
                'resolution_notes' => null,
                'customer_rating' => null,
                'customer_feedback' => null,
                'created_by' => 4,
                'created_at' => Carbon::now()->subHour(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'ticket_number' => 'TKT-2026-01-0005',
                'customer_id' => 4,
                'subscription_id' => 4,
                'caller_name' => 'Admin PT. Maju Bersama',
                'phone' => '081344444444',
                'email' => 'admin@majubersama.co.id',
                'category' => 'technical',
                'priority' => 'critical',
                'subject' => 'Internet mati total - Urgent! ',
                'description' => 'Internet kantor mati total sejak pagi. Sangat mengganggu operasional.  Mohon segera ditangani.',
                'status' => 'assigned',
                'assigned_to' => 4,
                'assigned_at' => Carbon::now()->subMinutes(30),
                'resolved_at' => null,
                'closed_at' => null,
                'sla_due_date' => Carbon::now()->addHours(2),
                'resolution_notes' => null,
                'customer_rating' => null,
                'customer_feedback' => null,
                'created_by' => 4,
                'created_at' => Carbon::now()->subMinutes(45),
                'updated_at' => now(),
            ],
        ];

        DB::table('tickets')->insert($tickets);
    }
}